### PR TITLE
This brings the package up to date, creates a test suite

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by ollef** [comment]
That's awesome! I didn't expect to see this, but it's more than welcome. I'll grant you access here and on Hackage, just in case. :)

**Comment by ddssff** [comment]
Thanks!  By the way, do you know if this is in use?

**Comment by ollef** [comment]
Not that I'm aware of. Are you planning on using it?

**Comment by ddssff** [comment]
I might use it to parse logic expressions in an automatic theorem prover library.

λ pPrint [fof| ∀x. (∀y. (x=y)) |]
∀x y. x=y
λ pPrint [fof| ∀x. ∀y. (x=y) |]
**\* Exception: (line 1, column 5):
unexpected "\8704"
expecting "(", expression, identifier, "nil", integer, "<", "|--", "true" or "false"

**Pull request merged**
